#pragma once
#include <Windows.h>

PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX CreateGLPIXStruct(LOGICAL_PROCESSOR_RELATIONSHIP, PDWORD);
DWORD ProcessorTopology(LOGICAL_PROCESSOR_RELATIONSHIP, PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, DWORD);
DWORD NumaTopology(LOGICAL_PROCESSOR_RELATIONSHIP, PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, DWORD);
void GroupTopology(LOGICAL_PROCESSOR_RELATIONSHIP, PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, DWORD);
DWORD CountSetBits(ULONG_PTR);